from datetime import datetime
from typing import Literal

from pydantic import BaseModel


class RAGResponse(BaseModel):
    """Structured output for a single RAG query.

    Generated by the LLM via structured output (not free-form text), so it can
    be consumed consistently across CLI, API, and Telegram bot without fragile
    manual text parsing. The `sources` field makes answers traceable back to
    what was actually retrieved, as evidence against hallucination.
    """

    answer: str
    confidence: Literal["high", "medium", "low"]
    sources: list[dict]
    """Each item shapes like:
    {"type": "news", "title": ..., "url": ...} or
    {"type": "price_data", "coin_id": ..., "date": ...}
    """
    coins_mentioned: list[str]
    generated_at: datetime
    query: str
